/*
   SPDX-License-Identifier: Apache-2.0
   Copyright Authors of NanhuInsight
*/

// Code generated by client-gen-v0.31. DO NOT EDIT.

// This package contains the scheme of the automatically generated clientset.
package scheme
