/*
   SPDX-License-Identifier: Apache-2.0
   Copyright Authors of NanhuInsight
*/

// Code generated by client-gen-v0.31. DO NOT EDIT.

// Package fake has the automatically generated clients.
package fake
