/*
   SPDX-License-Identifier: Apache-2.0
   Copyright Authors of NanhuInsight
*/

// Code generated by lister-gen-v0.31. DO NOT EDIT.

package v1alpha1

// DemoListerExpansion allows custom methods to be added to
// DemoLister.
type DemoListerExpansion interface{}

// DemoNamespaceListerExpansion allows custom methods to be added to
// DemoNamespaceLister.
type DemoNamespaceListerExpansion interface{}
