/*
   SPDX-License-Identifier: Apache-2.0
   Copyright Authors of NanhuInsight
*/

// Code generated by client-gen-v0.31. DO NOT EDIT.

// This package has the automatically generated fake clientset.
package fake
