apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasks.isg.zjlab.io
spec:
  group: isg.zjlab.io
  names:
    kind: Task
    plural: tasks
    singular: task
    shortNames:
      - t
    categories:
      - custom
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                job_id:
                  type: string
                job_name:
                  type: string
                user_name:
                  type: string
                cluster_name:
                  type: string
                is_cron:
                  type: boolean
                template_name:
                  type: string
                template_id:
                  type: integer
                ip_list:
                  type: string
                base_ip:
                  type: string
                mode:
                  type: string
                resource:
                  type: string
                status:
                  type: string
                create_time:
                  type: string
                finish_time:
                  type: string