/*
   SPDX-License-Identifier: Apache-2.0
   Copyright Authors of NanhuInsight
*/

// Code generated by informer-gen-v0.31. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	internalinterfaces "github.com/zjnc-tech/NanhuInsight/apis/client-go/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/zjnc-tech/NanhuInsight/apis/client-go/listers/demo/v1alpha1"
	versioned "github.com/zjnc-tech/NanhuInsight/apis/client-go/versioned"
	demov1alpha1 "github.com/zjnc-tech/NanhuInsight/apis/k8s/demo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DemoInformer provides access to a shared informer and lister for
// Demos.
type DemoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DemoLister
}

type demoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDemoInformer constructs a new informer for Demo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDemoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDemoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDemoInformer constructs a new informer for Demo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDemoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().Demos(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().Demos(namespace).Watch(context.TODO(), options)
			},
		},
		&demov1alpha1.Demo{},
		resyncPeriod,
		indexers,
	)
}

func (f *demoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDemoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *demoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&demov1alpha1.Demo{}, f.defaultInformer)
}

func (f *demoInformer) Lister() v1alpha1.DemoLister {
	return v1alpha1.NewDemoLister(f.Informer().GetIndexer())
}
