/*
   SPDX-License-Identifier: Apache-2.0
   Copyright Authors of NanhuInsight
*/

// Code generated by informer-gen-v0.31. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/zjnc-tech/NanhuInsight/apis/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Demos returns a DemoInformer.
	Demos() DemoInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Demos returns a DemoInformer.
func (v *version) Demos() DemoInformer {
	return &demoInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
