name: Go Related Checks

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request: {}
  push:
    branches:
      # - main
      # - ft/main/**
  # Add this workflow to be triggered by merge queue events
  merge_group:

permissions: read-all

# 用于并发管理
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after || github.event.merge_group && github.run_id }} #将工作流分组
  cancel-in-progress: ${{ !github.event.merge_group }} #如果不是merge_group则会取消

jobs:
  go-mod:
    name: Check Go Modules
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: 1.24.2
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Check module vendoring
        run: |
          go mod tidy
  #go mod vendor
  #test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
  golangci:
    name: Lint Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: 1.24.2
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # v5.3.0
        with:
          # renovate: datasource=docker depName=golangci/golangci-lint
          version: v2.0.2
          skip-cache: true
          args: "--out-${NO_FUTURE}format colored-line-number --verbose" #--modules-download-mode=vendor
          # working-directory: go
  # precheck:
  # generate-api:
  # generate-k8s-api:
